services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 10

  fastapi:
    build:
      context: ./fastapi-app
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./fastapi-app:/app
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    depends_on:
      - fastapi
    volumes:
      - .nginx/site:/usr/share/nginx/html:ro
    ports:
      - "80:80"

volumes:
  pgdata: