version: "3.9"

services:
  db:
    image: postgres:15
    container_name: mydroponic-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydroponic
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  api:
    build: ./mydroponic
    container_name: mydroponic-api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://myuser:mypassword@mydroponic-db:5432/mydroponic
    networks:
      - backend
    env_file:
      - .env

  nginx:
    build: ./nginx
    container_name: mydroponic-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
